### PR TITLE
Quick & dirty ranking save

### PR DESCRIPTION
**Pull request by Azaret**
Push this asap in production, then an admin shall go in each old event ranking page to save it.  
Once it's done we will be able to break ranking system.

### CODE REVIEW

**Comment by Hartorn** [comment]
@Azaret Sorry, did not have time to reveiw this. 
Will check this week-end !

**Comment by Azaret** [comment]
My IDE supports eslint, but this project does not provide any coding style rules or any eslint configuration file. My IDE will automatically comply to the projet rules as soon as a configuration file is provided.

**Comment by WilliamDASILVA** [comment]
@Azaret The eslint configuration already exists: https://github.com/FightForSub/ffs-zera/blob/master/.eslintrc

**Comment by Azaret** [comment]
Hmm my bad, was trusting the IDE. Thanks.

**Pull request merged**
